users:
  - name: do-sgp1-ml-k8s-cluster-admin
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - kubernetes
          - cluster
          - kubeconfig
          - exec-credential
          - '--version=v1beta1'
          - '--context=default'
          - b918c4af-fb54-4370-8401-6c0eb6fe88be
        command: doctl
        env: null
        provideClusterInfo: false
clusters:
  - cluster:
      certificate-authority-data: >-
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOakF6TVRNeApNek0xTVRGYUZ3MDBOakF6TVRNeE16TTFNVEZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDK0VBcjRDc0dMRFg0SGJtSEVpeGNXL3BUcG5zY0h2aC84UjJVS3M4aWwzWmdzdmtiNAp5OEkvZ3ZnQXFIVVFDeWU5MEdCYmI3NEhiOVlQdXFqSDZseTNlM05YRFdTYUZmQ3lXN0RqN3gvRVhTOTdNMURjCkZDRVk2K04yQlhSTVhzMFNOVlRnTlFmcE9DMlQ0OHJUTTJSaktjcncrUktXeXl6UjVNTzIwVUpYK2M0Tjh0QS8KNFNJczhWRHRLcFp1bzNXQzVQbEt3NERzRmdnMkNZYkpZTDRpekVYNitpalRaL0d6VEFMdEZHTHBxMHBFWFdHYgo5WTZpM0lHUmJIS0Zub2ovTUFyZFFNSzREeVppZm8weStUdXNFR0xJcmRueFYzai90VzlnaWZtZStmTm9WWTRMCjl0SmpORmlxcmtnVjJVcDRsVHgzYXVXdzNXOWdVOWxjVlo2bEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlF3Y2lrSnN1WWJXUDIzbmF2Ywo1V0pZREVOTStUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFlMkpIR0pKQnBtcVhzTjBrTC9KUmZuR3lUNE5tCm04NFRNQWtBZTkzQnJLa0xheERIWG9aSjE4bWxzTGVsbmlZUWV2aGJmTXgreE9mdlNQdlNvL0tiWUxKdFpiRjkKNGxjUDhsZHhwWlBWRm95ZlVHak9xUHkrLzJUOHRVVHdEWkNPcnJTcEdEMjVibEZvMUNvTkE4cTlPKzJOVHJyMAo5QlR5VWVoWEVEV0VFTEp5d3BtRlNPSk50ckFzeFpUZUhqM29TYVJHM3pTcEtCUVlGS05xMzhlYVhTRmhWOWxXCk5rMWdxdmtnWW5ncUhiNUQxQ0J4U1plNHB1Qk5pVGhTdUFhTUd4dUh6dENWR3BQUnJOMUhvekxwbm1aYjVXQWsKSnFYaU1kZmFkeHl2a2FFTSs4TXZJUHEyWWgxeWpOSm9uNjlNZ1VZNlpFbStVNUEwSEhHenVqbmxudz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://b918c4af-fb54-4370-8401-6c0eb6fe88be.k8s.ondigitalocean.com
    name: do-sgp1-ml-k8s-cluster
contexts: []
apiVersion: v1
kind: Config
preferences: {}
current-context: do-sgp1-ml-k8s-cluster
